import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const API_BASE = 'https://amendment-windy-horse.abasthan.app';
const STORAGE_KEY = 'bongo-ai-chat-v1';
const suggestions = [{icon:'✦',text:'Nisaidie kuelewa jambo fulani'},{icon:'⌁',text:'Andika wazo la ubunifu'},{icon:'◈',text:'Nifafanulie kwa ufupi'}];
type Message={role:'user'|'ai';text:string;image?:string};
type PreparedImage={preview:string;blob:Blob;mimeType:string};

async function compressImage(file:File):Promise<PreparedImage>{const bitmap=await createImageBitmap(file);const max=1024;const scale=Math.min(1,max/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));const ctx=canvas.getContext('2d');if(!ctx)throw new Error('Imeshindikana kuandaa picha.');ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();let q=.72;let blob=await new Promise<Blob|null>(r=>canvas.toBlob(r,'image/jpeg',q));while(blob&&blob.size>900*1024&&q>.25){q-=.08;blob=await new Promise<Blob|null>(r=>canvas.toBlob(r,'image/jpeg',q));}if(!blob||blob.size>1024*1024)throw new Error('Picha ni kubwa sana. Chagua picha nyingine.');return{preview:URL.createObjectURL(blob),blob,mimeType:'image/jpeg'};}

function App(){const[message,setMessage]=useState('');const[messages,setMessages]=useState<Message[]>(()=>{try{const s=localStorage.getItem(STORAGE_KEY);const p=s?JSON.parse(s):[];return Array.isArray(p)?p:[]}catch{return[]}});const[loading,setLoading]=useState(false);const[error,setError]=useState('');const[copied,setCopied]=useState(false);const[image,setImage]=useState<PreparedImage|null>(null);
useEffect(()=>{try{localStorage.setItem(STORAGE_KEY,JSON.stringify(messages))}catch{}},[messages]);
async function chooseImage(e:React.ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];e.target.value='';if(!file)return;if(!file.type.startsWith('image/'))return setError('Tafadhali chagua picha.');if(file.size>20*1024*1024)return setError('Picha ni kubwa sana. Tumia picha isiyozidi 20 MB.');try{setError('');if(image)URL.revokeObjectURL(image.preview);setImage(await compressImage(file))}catch(err){setError(err instanceof Error?err.message:'Imeshindikana kuandaa picha.')}}
function removeImage(){if(image)URL.revokeObjectURL(image.preview);setImage(null)}
async function sendMessage(e?:React.FormEvent){e?.preventDefault();const text=message.trim()||(image?'Eleza picha hii kwa undani.':'');if(!text||loading)return;const attached=image;setMessages(p=>[...p,{role:'user',text,image:attached?.preview}]);setMessage('');setLoading(true);setError('');try{let response:Response;if(attached){response=await fetch(`${API_BASE}/api/vision?message=${encodeURIComponent(text)}`,{method:'POST',headers:{'Content-Type':attached.mimeType},body:attached.blob})}else{response=await fetch(`${API_BASE}/api/chat`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text})})}const ct=response.headers.get('content-type')||'';const data=ct.includes('application/json')?await response.json():{error:`Server returned ${response.status} ${response.statusText}`};if(!response.ok)throw new Error(data.error||`Server returned ${response.status}`);setMessages(p=>[...p,{role:'ai',text:data.text||''}]);removeImage()}catch(err){setError(err instanceof Error?err.message:'Something went wrong.')}finally{setLoading(false)}}
function newChat(){setMessages([]);setError('');setMessage('');setCopied(false);removeImage();try{localStorage.removeItem(STORAGE_KEY)}catch{}}async function copyLast(){const last=[...messages].reverse().find(m=>m.role==='ai');if(!last)return;try{await navigator.clipboard.writeText(last.text);setCopied(true);setTimeout(()=>setCopied(false),1400)}catch{}}const started=messages.length>0||loading||!!error;
return <main className="app"><div className="ambient ambient-one"/><div className="ambient ambient-two"/><section className={`shell ${started?'chat-mode':''}`}><header className="topbar"><button className="brand-mark brand-button" type="button" onClick={newChat} aria-label="BONGO AI home"><div className="brand-orb">B</div><div><strong>BONGO</strong><span>AI</span></div></button><div className="top-actions"><div className="online"><i/> Online</div>{started&&<button className="new-chat" onClick={newChat} type="button">＋ New chat</button>}</div></header>{!started?<><div className="hero"><div className="eyebrow"><span>✦</span> BONGO AI</div><h1>Habari, <em>karibu.</em></h1><p className="tagline">Msaidizi wako wa akili wa kizazi kipya.</p><p className="intro">Uliza swali, eleza unachohitaji, au tuma picha.</p></div><div className="suggestions">{suggestions.map(i=><button key={i.text} type="button" onClick={()=>setMessage(i.text)}><span>{i.icon}</span>{i.text}<b>›</b></button>)}</div></>:<div className="conversation">{messages.map((m,i)=><article key={`${m.role}-${i}`} className={`message ${m.role}`}><div className="message-avatar">{m.role==='ai'?'B':'M'}</div><div className="message-body"><div className="message-name">{m.role==='ai'?'BONGO AI':'Wewe'}</div>{m.image&&<img className="message-image" src={m.image} alt="Picha iliyotumwa"/>}<p>{m.text}</p></div></article>)}{loading&&<article className="message ai"><div className="message-avatar">B</div><div className="message-body"><div className="message-name">BONGO AI</div><div className="thinking"><span/><span/><span/> Inachambua...</div></div></article>}{error&&<div className="error-card">{error}</div>}{messages.some(m=>m.role==='ai')&&!loading&&<button className="copy-btn" type="button" onClick={copyLast}>{copied?'✓ Imenakili':'⧉ Nakili jibu la mwisho'}</button>}</div>}{image&&<div className="attachment-preview"><img src={image.preview} alt="Preview ya picha"/><div><strong>Picha imeambatanishwa</strong><span>BONGO AI itaichambua</span></div><button type="button" onClick={removeImage} aria-label="Ondoa picha">×</button></div>}<form onSubmit={sendMessage} className="composer"><input id="bongo-image-input" type="file" accept="image/png,image/jpeg,image/webp,image/gif" onChange={chooseImage} hidden aria-label="Chagua picha"/><label className="composer-icon attach" htmlFor="bongo-image-input" role="button" tabIndex={0} aria-label="Ambatanisha picha">＋</label><input value={message} onChange={e=>setMessage(e.target.value)} placeholder={image?'Uliza kuhusu picha hii...':'Muulize BONGO AI chochote...'} aria-label="Andika ujumbe"/><button className="send" disabled={loading||(!message.trim()&&!image)} aria-label="Tuma ujumbe">{loading?'…':'↑'}</button></form><div className="hint">Tuma picha ili BONGO AI ichambue na kujibu maswali kuhusu picha hiyo.</div></section></main>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
